version: "3.9"
services:
  jenkins:
    container_name: jenkins
    build: .
    ports:
      - "8080:8080"
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=""
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
  jenkins-docker:
    container_name: docker
    image: "docker:dind"
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    privileged: true

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins:
