name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: circleci/node:12-browsers
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install required dependencies
        run: |
          yarn install --lockfile

      - name: Run test
        run: yarn test
