name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: circleci/node:12-browsers
      options: --user root
    steps:
      - uses: actions/checkout@v1

      - name: Install required dependencies
        run: yarn install --lockfile

      - name: Run test
        run: yarn test:ci

      - name: Create HTML report
        if: ${{ always() }}
        run: yarn test:report:generate

      - name: Archive HTML report
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: html report
          path: reports/allure/allure-report/**
